version: '2'
services:
  ua-app:
    image: ua
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ua-postgresql:5432/ua
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  ua-postgresql:
    extends:
      file: postgresql.yml
      service: ua-postgresql
